### PR TITLE
Related with issue #39 (Adapt to PSR-4)

### PR DESCRIPTION
**Pull request by obokaman-com**
- Move tests to "tests/Sifo" folder to reproduce the same structure under /src
- Apply correct namespace to /src/Sifo files (most of them keep the same namespace. Only those under /Cache and /Debug folders have changed.)
- Fix names for those classes under /Cache and /Debug folders.
- Separate some classes in multiple files (MysqlStatement for instance).
- Add sifo-common-instance
- Add coverall actions to travis config.

### CODE REVIEW

**Comment by obokaman-com** [comment]
Hi @lombartec & @alombarte! I've pushed some for you to review, related with the namespaces migration. Please, take a look to see if they could be merged to travis integration. 

Bests!

**Comment by nilopc** [comment]
I should say I'm happy to see the direction SIFO is taking. I so much needed it. 

Keep up the good work.

**Comment by obokaman-com** [comment]
@nilopc agree about stop supporting PHP <5.6 :+1:

**Comment by alombarte** [comment]
I'll merge it right away.

Removing all non-sifo libs was something needed. Additionally to this we should at least in the documentation say that some Sifo files might have dependencies.

E.g: If I want to use the `Mail` class this has a dependency with PHPMailer. ( http://sifo.me/API/Mail )

**Comment by alombarte** [comment]
About removing support for PHP <5.6 I am good with it. The only comment around this is that although PHP keeps moving forward, not all distros are. For instance in a shiny CentOS 7.1 all you can have is a PHP 5.4.16. I usually work out of the default packaging, but I thought it was worth mentioning it.

Some distros and version that would be affected:
- Previous Debian 7 (PHP 5.4.4). Current Debian 8 with 5.6.7
- Previous Ubuntu 14 (5.5.10). Current Ubuntu 15 with 5.6.4
- Centos. All versions affected
- FreeBSD. All versions affected

http://distrowatch.com/table.php?distribution=centos

**Comment by alombarte** [comment]
Thank you everyone!

I merged the branch namespaces-migration and now you have the code in
travis-integration. Whenever you think it's a little bit safe I would
suggest merging travis branch into devel and work from there.

I am also happy to see the direction this is taking. I wanted to do it long
time ago but I have been a litlle bit offline. Thank you all for making it
real.



2015-10-10 0:59 GMT+02:00 Albert Garcia <notifications@github.com>:

**Pull request merged**
