### PR TITLE
Add Filter namespace

### PR DESCRIPTION
**Pull request by lombartec**
- Move all filter classes to Sifo\Filter namespace
- Create a new file per each class inside the Filter.php file
- Add use statements for the new namespace where needed

### CODE REVIEW

**Comment by lombartec** [comment]
Applied some of your feedback at PR #64 here too.

What do you thinkg about the `Sifo\Filter\Filter` class? maybe move it back to `Sifo\` root namespace?

**Comment by alombarte** [comment]
Yes, I would certainly had chosen to have Filter in the root.

**Comment by obokaman-com** [comment]
It seems that `src/Sifo/FilterException.php` namespace doesn't correspond to its location.

**Comment by lombartec** [comment]
@obokaman-com thanks for pointing it out! :smile:

**Pull request merged**
