### PR TITLE
Move all inheritors from SEOException to it's own class

### PR DESCRIPTION
**Pull request by lombartec**
- Move all classes inside the `Exceptions.php` file to it's own file.
- Keep main logic of `Exceptions.php` by adding it into a new `SEOException` class.
- Change classes that used `Exceptions` class or any of it's inheritors.

### CODE REVIEW

**Comment by lombartec** [comment]
Just a bulk change, I think we should change (when everything is working) all this Exception files to a class that we can use just like this:

```php
throw new HttpException(404);
``` 

or

```php
$httpException->throw(302);
``` 

or whatever we find useful :smile:

**Comment by obokaman-com** [comment]
One suggestion: taking into account that this change will already require that we update our instances code to call old "SEO_Exceptions" with the new namespace, what do you think about removing this "SEO" prefix? Most of HTTP exception codes have nothing to do with SEO, and I think that it was a reminiscence of the original FW name (SeoFramework). We can place the main SEOException class (maybe as an abstract class?) in the /src/Sifo folder as \Sifo\Exception, and all the other defined exceptions under /src/Sifo/Exception folder, keeping only , so we will call/use them as \Sifo\Exception\500. 

I doubt about the final classes names... I think it would be better to keep cleaner names, avoiding repeat the context in the class name (\Sifo\Exception\500 over \Sifo\Exception\Exception500). The problem with this is that we will have calls to `throw new 500($message)` on our code, although we can take profit of alias on the `use` statement (`use \Sifo\Exception\500 as 500Exception` for instance). What do you think?

**Comment by obokaman-com** [comment]
BTW, @lombartec, totally agree with your proposal.

**Comment by lombartec** [comment]
@obokaman-com What about:

Sifo\Exception\Http\500, Sifo\Exception\Http\404, etc, and
Sifo\Exception\HttpException (being this the parent class of all under the Http namespace?

**Comment by lombartec** [comment]
For the moment I just added one more commit to replace SEO with HTTP until we define how to better organize this kind of Exceptions.

**Comment by alombarte** [comment]
The Exception naming `Sifo\Exception\Http\NotFound.php` is the one I like the most. And yes, the `SEO` preffix is a survivor from 2009 (no kidding). Kill it with fire!

**Comment by JavierCane** [comment]
+1 for the `Sifo\Exception\Http\NotFound.php` naming for the current renaming and +1 for the `throw new HttpException(404);` option in a future refactor.

Not so convinced of not repeating the "main concept" of the class in cases like the `Sifo\Exception\500` proposal or a possible `Sifo\Http\Exception` because of the loss of context. I think that having to specify the alias in the `use` statement like `use \Sifo\Exception\500 as Exception500` or `use \Sifo\Http\Exception as HttpException` in each usage of the class is a little bit annoying. So I would bet more for an option which provides a little bit more of context even if that implies sacrificing the no duplication in the full namespace like `Sifo\Exception\Exception500` or `Sifo\Http\HttpException` (in wich case, I would go for the later one).

Cheers with the good work guys!

**Comment by obokaman-com** [comment]
Great! Good work @lombartec ;-)

**Pull request merged**
